### ISSUE TITLE
Proptypes has been moved to a separate package - Expo 19

### ISSUE THREAD

**Issue by siwel** [EvanBacon/expo-three-orbit-controls#1]
Using the example on expo 19 I get this warning;

<img width="306" alt="screen shot 2017-08-18 at 21 37 39" src="https://user-images.githubusercontent.com/6073481/29476838-b8bc480e-845d-11e7-94e0-bf54fd606b11.png">

**Comment by Kif11** [comment]
I made a pull request addressing this issue https://github.com/EvanBacon/expo-three-orbit-controls/pull/2

**Comment by EvanBacon** [comment]
Thanks @Kif11 <333
