### ISSUE TITLE
Question: Only allow to orbit horizontally

### ISSUE THREAD

**Issue by cardiohelge** [EvanBacon/expo-three-orbit-controls#9]
Hey, thank you for your work on this library. It helps alot 👍 .

I was wondering if you have an idea, how I can stop the camera from moving vertically and only allow to horizontally orbit the object?

**Comment by cardiohelge** [comment]
I solved my question by using the ref to the OrbitControls directly.

**Comment by timnlupo** [comment]
@cardiohelge How did you accomplish this?

**Comment by cardiohelge** [comment]
I am using Functional Component, so I get the ref through useRef. I then set the OrbitControlsView ref prop, and finally i could get the controls in the render function in GLView.

```
const orbitterRef = useRef()

// ...
<OrbitControlsView ref={orbitterRef} ...>
  <GLView onContextCreate={(gl) =>
    ...
    const render = () => {
        const controls = orbitterRef?.current?.getControls();
        controls.maxPolarAngle = Math.PI / 2.5;
        controls.minPolarAngle = Math.PI / 2.5;
        // Here you can use all functionality from OrbitControls in THREE.js
        ...
    }
} />
```

**Comment by AngelSan19** [comment]
@cardiohelge do you have a complete example? I'm trying, but don't work

Thanks :)

**Comment by p4tric** [comment]
@cardiohelge, waiting for your complete example as well.

**Comment by cardiohelge** [comment]
Something like this. Note that the asset is not included, but this does work with any other asset. Does not need to be a BHV file. Hope this helps. 👍 

[Link to the Gist](https://gist.github.com/cardiohelge/e12fcf9c07ec8accaec4bd06abc9b6f1)
